name: Debug build CI
on:
  push:
    branches:
      - 'master'

jobs:
  test_and_build:
    name: Run Unit Tests & Generate APK
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradlecache-v2-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradlecache-v2
      - name: Run KtLint
        run: bash ./gradlew ktlintCheck
      - name: Run detekt
        run: bash ./gradlew detekt
      - name: Unit tests
        run: bash ./gradlew -Pci --console=plain test --stacktrace
      - name: Instrumented tests
        run: bash ./gradlew -Pci --console=plain connectedAndroidTest --stacktrace
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace